### PR TITLE
Create Current_File_Validator_V2

### PR DESCRIPTION
**Pull request by pbreads0316**
Uploading the code as a branch off CBIIT/nci-seronet-validator

### CODE REVIEW

**Comment by n2iw** [comment]
- Please add .py extension for the file
- function lambda_handler is a little too long, it would be better to extract out some helper functions if possible.
- Line 35, put remaining lines in the function in try block, and close connections in finally block. So connections will always be closed properly, no matter what exception might happen.
- Line 49, a "f-string" would be more desirable  
- Line 45, string "On" was used multiple times in the code, better to define a constant and use that instead of string literals.
- Line 91, "enumerate" is not necessary, "for row_data in rows:" should work
- Line 102, CBC_ZIP_filename was not used anywhere
- Line 192, submit_file_count was not used anywhere
- Line 219, new_key was assigned twice
- Line 371: parameter row_idex and filename were not used

**Comment by n2iw** [comment]
A more important change we need to do is to use parameters in all SQL statements, and utilize "prepared statement". This is security measure to prevent "SQL injection".

**Comment by pbreads0316** [comment]
Thank you for feedback will make changes you mentioned

**Comment by n2iw** [comment]
Replaced by PR #5

**Pull request closed without merging**
